### ISSUE TITLE
Remove LSWeather from the Lockscreen

### ISSUE THREAD

**Issue by 2Qt2beStr8** [ajatkj/scriptable#17]
Hi,
i have a stupid question. How can i remove LSWeather from the Lockscreen. I have deinstalled the Scriptable and Shortcut App and did a reboot, but LSWeather is still visible at the Lockscreen. I have no idea how to remove it :-(

thanks for a answer. 

best regards
DJ

**Comment by ajatkj** [comment]
Hi @2Qt2beStr8 you just need to change the wallpaper to something else. The scripts adds a overlay to the wallpaper and sets on your lock screen so just changing lock screen should be enough.

**Comment by 2Qt2beStr8** [comment]
@ajatkj thank you very much!
