### ISSUE TITLE
Script and shortcut for iOS 15

### ISSUE THREAD

**Issue by 2Qt2beStr8** [ajatkj/scriptable#19]
Hi,
did you Update the Script and the shortcut for iOS 15?

Best regards
DJ

**Comment by ajatkj** [comment]
Hi, I have only updated the LSMatrix shortcut for iOS 15. The shortcut app on iOS 15 Beta is still very unstable so unable to edit other shortcuts. Will update others after Shortcut app stablizes.

**Comment by 2Qt2beStr8** [comment]
Hi, thank you for this information. iOS 15 is released today and i hope the shortcut app is now stable.

**Comment by ajatkj** [comment]
Surprisingly and unfortunately the issue with Shortcuts is not fixed. The editor still has lots of bugs!
![image](https://user-images.githubusercontent.com/8344288/133878875-8bf29f99-08a2-458e-b0df-067373791cd0.png)

**Comment by 2Qt2beStr8** [comment]
Unfortunately, that doesn't sound so good. Then I will definitely not update to iOS 15, because without LSWeather I can no longer live :-)

**Comment by ajatkj** [comment]
Haha. Thanks. Apparently there are problems with Scriptable app on iOS 15 as well. Lot of my scripts are not running or running incorrectly.

**Comment by 2Qt2beStr8** [comment]
I hope Apple will fix this asap

**Comment by ajatkj** [comment]
I have updated all the shortcuts to work for iOS 15. You can download using the links in readme. Make sure to update scriptable to latest version as well (fixes issue with colors of SF symbols). I haven't made any changes to the script itself so you don't need to update those.

**Comment by 2Qt2beStr8** [comment]
Hi @ajatkj,
I updated my iPhone to iOS 15.1 and then installed the new shortcut. Unfortunately, I always get this error message.

![EC69C5CB-6411-4C91-BB11-8DD0DEB91A01](https://user-images.githubusercontent.com/20930745/139555563-869fb9f4-7456-4726-99ac-60d9eb81b9b9.jpeg)

However, the script can be executed in Scriptable without any problems

**Comment by 2Qt2beStr8** [comment]
I fixen the Problem :-)

**Comment by ajatkj** [comment]
Glad you fixed it. What was the problem?

**Comment by 2Qt2beStr8** [comment]
Apparently in iOS 15 it is no longer possible to enable the background image from iCloud. After I enabled Photos, it worked without any problems.
