### ISSUE TITLE
Change weather icon colors

### ISSUE THREAD

**Issue by kolbydayley** [ajatkj/scriptable#20]
I am struggling to find where I can change the weather icon colors.  Mine are black, whereas all of the text is white.

**Comment by ajatkj** [comment]
Hi, I have used SFSymbols for all glyphs and unfortunately iOS 15/Scriptable on iOS 15 has issues so all SFSymbols are appearing black. Unfortunately unless Scriptable or iOS fixes something we cannot do anything 😞

**Comment by ajatkj** [comment]
Hi, Simon has released an update to Scriptable for this issue. It should work fine after the update.

**Comment by kolbydayley** [comment]
Wow,  that is great news.  How did you get in touch with Simon so fast to get him to publish a fix? I have another fix that I want to suggest that is not related to your wonderful script.

**Comment by ajatkj** [comment]
Haha, sorry if I led you to believe that I had something to do with this. The issue is known for a while now (since iOS 15 beta came out) but I guess he finally got time to fix this now (he is busy with other apps). You can raise your issue with the in-app contact page though.
