### ISSUE TITLE
Cannot get weather data

### ISSUE THREAD

**Issue by Biscoooooooooo** [ajatkj/scriptable#25]
![IMG_1768](https://github.com/ajatkj/scriptable/assets/93252394/1d361c28-60ea-4bd1-8949-b5c8bd34c11b)
![IMG_1767](https://github.com/ajatkj/scriptable/assets/93252394/69c4c6a5-22b0-49f0-bfa3-2ac32df0ecf2)

**Comment by ajatkj** [comment]
Apparently, the API version for openweather has changed to 3.0.. You can update this in the above file-

From
`const baseWeatherURL='https://api.openweathermap.org/data/2.5/onecall';`

to 
`const baseWeatherURL='https://api.openweathermap.org/data/3.0/onecall';`

I will push an update to the scripts soon.

**Comment by Biscoooooooooo** [comment]
I change it to 3.0 but it is still not working 
![image](https://github.com/ajatkj/scriptable/assets/93252394/a88797ad-77fc-4d0d-9827-02a20febb7e0)

**Comment by ajatkj** [comment]
Do you see any errors when you run the script in scriptable? Unfortunately, I don't have a device right now where I can test this myself but should be available in few days.

**Comment by Biscoooooooooo** [comment]
I changed it
But I still can’t get data

**Comment by ajatkj** [comment]
Apparently your old openweather api key won't work with 3.0 API call. You will need to "Subscribe" to openweather's new "One Call API 3.0" subscription which offers 1000 free API calls per day and charges there after. 

More information [here](https://home.openweathermap.org/subscriptions).

I have been meaning to rewrite these scripts to use weather data from shortcuts app and pass it on to scriptable but haven't got much time to work on it yet. Hopefully sometime in the near future.

**Comment by Biscoooooooooo** [comment]
So I need to 「subscribe」it ?
